[package]
name = "pride-overlay"
description = "overlay pride flags on images"
version = "4.0.0"
edition = "2024"

authors = ["newt <hi@newty.dev>"]
keywords = ["pride", "lgbtq", "flags", "image-processing", "graphics"]
categories = ["graphics", "multimedia::images"]

repository = "https://github.com/isitreallyalive/pride-overlay"
readme = "readme.md"
license-file = "license.md"
